### ISSUE TITLE
The module is not showing a result in my MMM

### ISSUE THREAD

**Issue by kruemel68** [fruestueck/MMM-WeatherDependentClothes#1]
If I enter a header in the config, the header is shown, but nothing other is coming out of the module.
Please help
Currentweather is properly working.
location and appid are correct copied.

**Comment by fruestueck** [comment]
Hi kruemel,
thats odd. Tested it right now and it worked for me. Could you check the formatting. Possibly there is a symbol (comma,...) missing. If this doesn't help, upload your config.js code and don't forget to annoymize any keys.

**Comment by kruemel68** [comment]
Hello,

checked all the formatting and I think I am OK.
Attached is the config.js.

Keys and Pas are replaced.

Thanks a lot for help.

Jörn

[config.js.txt](https://github.com/fruestueck/MMM-WeatherDependentClothes/files/4533433/config.js.txt)

**Comment by fruestueck** [comment]
```
preferences: [
	{
		name: "Winter jacket",
		icon: "jacket-cold",
		conditions: {
		temp_max: 2.0, // <--- is it colder than 2°C?
		}
	},
	// if not, nothing will be displayed
	// <--- more items here. See .js for default list
]
```

There is nothing wrong with your config file (afaik). Everything works as intendet. But your **preferences** (in config.js, for the module) defines only one clothing item, a winter jacket. And as its condition (temperature below 2°C) is not fulfilled, it's not displayed. Well and there is nothing else defined in that list.

You simply have to add more clothes to your preferences list (as the default list is beeing overruled with the config.js preferences list):

- You could copy some from the default list (view [MMM-WeatherDependentClothes.js](https://github.com/fruestueck/MMM-WeatherDependentClothes/blob/master/MMM-WeatherDependentClothes.js))
- You could delete your preferences list in the config.js to use the default clothing specified in the module js file
- You could also create your own Icons (currently PNG supported) and custom clothing preferences

Let me know if that does the trick or if you need anything.

Thanks to your message I was able to find a nother unrelated issue.
Also, there could be the need for user feedback if no clothing matches the weather.

**Comment by kruemel68** [comment]
Thanks a lot !
Thats solved it.

**Comment by fruestueck** [comment]
Das freut mich. : )
